FROM golang:1.10.3

WORKDIR /tmp

RUN curl -O https://get.docker.com/builds/Linux/x86_64/docker-1.13.1.tgz && \
  tar -xzf docker-1.13.1.tgz && \
  mv docker/docker /usr/local/bin/docker && \
  rm -rf ./docker && \
  go get -u github.com/golang/dep/cmd/dep && \
  go get -u gopkg.in/alecthomas/gometalinter.v2 && \
  gometalinter.v2 --install

# Install kubectl
RUN curl -o /kubectl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && \
    chmod +x /kubectl && mv /kubectl /usr/local/bin/kubectl
